version: "3.0"
services:

  busybox:
    container_name: busybox
    image: busybox
    volumes:
      - ./app:/var/www/html
    working_dir: /var/www

  server:
    image: apache
    container_name: server
    ports:
      - 80:80
    environment:
      - APACHE_DOCUMENT_ROOT=/var/www/html/app/public
    build:
      context: .
    depends_on:
      - database
    volumes:
      - ./app:/var/www/html
      - ./config/vhost.conf:/etc/apache2/sites-available/000-default.conf

  database:
    image: mysql:5.7
    container_name: mysql
    environment:
      MYSQL_DATABASE: portfolioblog_db
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306

  mailcatcher:
    container_name: mailcatcher
    image: schickling/mailcatcher
    ports:
      - 1080:1080
      - 1025:1025
